apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "34.135.240.58.nip.io"
    http:
      paths:
      - path: /projects/*
        pathType: Prefix
        backend:
          service:
            name: project-main-service
            port:
              number: 8100
      - path: /counts/*
        pathType: Prefix
        backend:
          service:
            name: project-counter-service
            port:
              number: 8101
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: pms-tool-ui-service
            port:
              number: 3000
      - path: /notifications/*
        pathType: Prefix
        backend:
          service:
            name: project-notification-service
            port:
              number: 8102
              
              
              
      
